### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Khyota** [pinry/docker-pinry#18]
Tried to run as per the instructions but it fails with an import error. I'm assuming that is the cause.

# docker run -p=10000:80 -v=/mnt/pinry:/data pinry/pinry /start
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-02-26 23:47:31,550 CRIT Supervisor running as root (no user in config file)
2018-02-26 23:47:31,550 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2018-02-26 23:47:31,550 WARN Included extra file "/etc/supervisor/conf.d/uwsgi.conf" during parsing
2018-02-26 23:47:31,614 INFO RPC interface 'supervisor' initialized
2018-02-26 23:47:31,615 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-02-26 23:47:31,615 INFO supervisord started with pid 14
2018-02-26 23:47:32,619 INFO spawned: 'nginx' with pid 17
2018-02-26 23:47:32,625 INFO spawned: 'uwsgi' with pid 18
2018-02-26 23:47:33,858 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 23:47:33,859 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by overshard** [comment]
Please try with the most recent updates from @haoling it should be fixed
