### ISSUE TITLE
No module named django.core.management

### ISSUE THREAD

**Issue by dominicjprice** [pinry/docker-pinry#19]
Hi, I'm trying with the latest version (467487b) and I'm getting the following error:

> Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
/usr/local/pyenv/versions/2.7.14/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-04-17 13:25:14,170 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2018-04-17 13:25:14,170 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2018-04-17 13:25:14,170 INFO Included extra file "/etc/supervisor/conf.d/uwsgi.conf" during parsing
2018-04-17 13:25:14,437 INFO RPC interface 'supervisor' initialized
2018-04-17 13:25:14,444 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-04-17 13:25:14,474 INFO supervisord started with pid 93
2018-04-17 13:25:15,476 INFO spawned: 'nginx' with pid 137
2018-04-17 13:25:15,486 INFO spawned: 'uwsgi' with pid 138
2018-04-17 13:25:16,576 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-04-17 13:25:16,577 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by winkidney** [comment]
Hi, 
It should be fixed after a while.

I have submit a pull request to fix the problem.

You can just install latest version of Pinry(with many bug fixes and small features).

https://github.com/pinry/docker-pinry/pull/20

**Comment by winkidney** [comment]
fixed, closed
