### ISSUE TITLE
Internal Server Error on fresh installation

### ISSUE THREAD

**Issue by h4ng0ver** [pinry/docker-pinry#5]
Hi

I am getting an Internal Server Error on http://mydockerhost:10000 after a fresh installation.
I followed your installation guide: https://github.com/pinry/docker-pinry/blob/master/README.rst

The output of the docker container:

lars@peter:~/docker/data/pinry$ docker run -p=10000:80 -v=/home/lars/docker/data/pinry:/data pinry/pinry /start                                       [25/1963]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named south
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
django.setup()                                                                                                                                     [2/1963]
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/www/pinry/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named south
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in defau
lt locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for im
proved security.
  'Supervisord is running as root and it is searching '
2016-02-06 20:29:02,429 CRIT Supervisor running as root (no user in config file)
2016-02-06 20:29:02,429 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2016-02-06 20:29:02,429 WARN Included extra file "/etc/supervisor/conf.d/uwsgi.conf" during parsing
2016-02-06 20:29:02,449 INFO RPC interface 'supervisor' initialized
2016-02-06 20:29:02,449 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-02-06 20:29:02,449 INFO supervisord started with pid 21
2016-02-06 20:29:03,451 INFO spawned: 'nginx' with pid 24
2016-02-06 20:29:03,454 INFO spawned: 'uwsgi' with pid 25
2016-02-06 20:29:04,528 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-02-06 20:29:04,528 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

I am new to docker, django an python. But maybe I can help fix it when you can give me some hints to start :

**Comment by overshard** [comment]
I've working on a large amount of updates to Pinry and I haven't updated the settings that this project uses yet. I'll fix it soon as I finish some of the other updates for the core Pinry. If you wish to try and fix it yourself it's the `pinry/settings/__init__.py` and `pinry/settings/production.py` files that need to be updated with the latest files from the core `pinry` project but modified slightly for running with docker.

**Comment by frolov152** [comment]
Hi overshard,
Could you give us a clue, what kind of modifications we are talking about?
In the instruction there is nothing about SECRET_KEY field from production.py
Is the one from /mnt/pinry/ should go there? With or without quotes?
Thanks in advance. Newbee for all that staff too.

**Comment by overshard** [comment]
I'll get this updated this weekend, busy week for me, I keep forgetting to do it! I'll let you know the progress. Shouldn't take me long once I have a break from the work week.

**Comment by frolov152** [comment]
Thank You!
Will wait. Please, tell us, what we will need to do to upgrade our installation after that.

**Comment by overshard** [comment]
The only updates that are required are that you add `ALLOWED_HOSTS = ['*']` to your `pinry/settings/production.py` file and remove `'south',` from 'INSTALLED_APPS` IN `pinry/settings/__init__.py`. I also had to move from syncdb to migrate in the start file. Upgrading really shouldn't be a problem since we store the data, images and the database, on a mnt outside of the docker instance.

I'm working on a full update still.

**Comment by frolov152** [comment]
overshard, thanks for the update. I'm doing something wrong, probably. I did copy __init__.py and production.py from the core pinry project. I did add the line you told. There is no 'south' in __init__.py (should it be renamed to init.py?). No go still. Do we need to change SECRET_KEY = 'CHANGE-ME' line in production.py?

**Comment by DanielBrierton** [comment]
I've tried making those changes too, and still hitting problems, but different problems.

I noticed that since 1.3.0 (the version that docker-pinry seems to be coded towards based on commit history), you've moved from including your client-side dependencies in the repo to using bower. This docker image doesn't have node, npm or bower, and doesn't run `bower install`, so these files are missing, which seems to be resulting in 500 errors because it tries to compress the files before sending them to the client.

**Comment by frolov152** [comment]
Hi Daniel,
As you know much mare, then I, about this staff, could you share steps, you did?
Can't pass Internal Server Error still.
Thanks in advance.

**Comment by overshard** [comment]
Seems like the other issue is that we now require bower to install some JS libs we use on the front end, that's not being done so an error occurs because django-compressor doesn't finding all the static files to compress. I'm doing a final few builds and pushing an update soon that fixes everything.

**Comment by overshard** [comment]
Should be fixed in the latest update b5948a82be5c33a7318b7f22d28873cfa38a8bdc
